version: '3'

services:
  loadbalancer:
    image: dockercloud/haproxy:1.2.1
    ports:
      - "80:80"
    links:
      - catalogapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - catalogapi_network
  catalogapi:
    image: catalogapi
    build:
      context: ./CatalogApi
      dockerfile: Dockerfile
    networks:
      - catalogapi_network
    
#  mongodb:
#    image: mongo
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGODB_ROOT_USERNAME=dbadmin
#      - MONGODB_ROOT_PASSWORD=password
#      - MONGODB_ROOT_ROLE=root
#      - MONGODB_USERNAME=webrole
#      - MONGODB_PASSWORD=password
#      - MONGODB_DBNAME=catalog
#      - MONGODB_ROLE=readwrite
#    networks:
#      - catalogapi_network

networks:
  catalogapi_network:
    driver: bridge